vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 4
  }
}

posts: {
  shape: sql_table
  title: string {constraint: required}
  description: string {constraint: required}
  pubDate: date {constraint: required}
  updatedDate: date
  image: Image
  imageAlt: string
  tags: "string[]"
  relatedPosts: "reference[]"
  isDraft: boolean
  isFeatured: boolean
  body: markdown {constraint: required}
}
